# Generated by Django 3.2.4 on 2021-07-06 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200612_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_path', models.CharField(blank=True, max_length=225, null=True, verbose_name='Category Path')),
                ('category', models.CharField(blank=True, max_length=125, null=True, verbose_name='Category')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='Title')),
                ('publish_place', models.CharField(blank=True, max_length=65, null=True, verbose_name='Publish Place')),
                ('publish_date', models.DateField(verbose_name='Publish Date')),
                ('dimensions', models.CharField(blank=True, max_length=225, null=True, verbose_name='Dimentions')),
                ('color', models.CharField(blank=True, max_length=65, null=True, verbose_name='Color')),
                ('condition', models.CharField(blank=True, max_length=125, null=True, verbose_name='Condition')),
                ('short_desc', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('long_desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.FloatField(default=None, null=True, verbose_name='Price')),
                ('price_currency', models.CharField(blank=True, max_length=3, null=True, verbose_name='Color')),
                ('img_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Image')),
                ('author', models.CharField(blank=True, max_length=125, null=True, verbose_name='Author')),
                ('author_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Author URL')),
                ('attributes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Attribute')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Origin URL')),
            ],
        ),
    ]
