# Generated by Django 3.2.4 on 2021-06-15 07:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200612_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=125, null=True, verbose_name='Product Code')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Name')),
                ('first_review_date', models.DateField(blank=True, null=True, verbose_name='First Review Date')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Shop Url')),
                ('update_at', models.DateField(blank=True, null=True, verbose_name='Update at')),
                ('table_name', models.CharField(blank=True, default='product', max_length=65, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shop Name')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Shop Url')),
                ('product_no', models.PositiveIntegerField(default=0, verbose_name='Number of products')),
                ('sale_no', models.PositiveIntegerField(default=0, verbose_name='Number of sales')),
                ('review_no', models.PositiveIntegerField(default=0, verbose_name='Number of review')),
                ('author', models.PositiveIntegerField(default=0, verbose_name='Number of review')),
                ('update_at', models.DateField(blank=True, null=True, verbose_name='Update at')),
                ('table_name', models.CharField(blank=True, default='shop', max_length=65, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=125, null=True, verbose_name='Review Author')),
                ('stars', models.FloatField(default=0, verbose_name='Starts')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='Review date')),
                ('variants', models.CharField(blank=True, max_length=225, null=True, verbose_name='Variant')),
                ('content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Content')),
                ('update_at', models.DateField(blank=True, null=True, verbose_name='Update at')),
                ('table_name', models.CharField(blank=True, default='review', max_length=65, null=True)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review_product', to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_shop', to='app.shop'),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125, verbose_name='Keyword')),
                ('rank', models.CharField(max_length=125, verbose_name='Rank')),
                ('update_at', models.DateField(blank=True, null=True, verbose_name='Update at')),
                ('table_name', models.CharField(blank=True, default='keyword', max_length=65, null=True)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='keyword_product', to='app.product')),
            ],
        ),
    ]
