# Generated by Django 3.2.4 on 2021-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_mapdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title'),
        ),
    ]
