# Generated by Django 3.2.4 on 2021-06-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210615_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='table_name',
            field=models.CharField(blank=True, default='app_keyword', max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='table_name',
            field=models.CharField(blank=True, default='app_product', max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='table_name',
            field=models.CharField(blank=True, default='app_review', max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='table_name',
            field=models.CharField(blank=True, default='app_shop', max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
