# Generated by Django 3.2.4 on 2021-07-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_mapdata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdata',
            name='publish_date',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='mapdata',
            name='publish_place',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Publish Place'),
        ),
    ]
