# Generated by Django 3.2.4 on 2021-07-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='stars',
            field=models.FloatField(default=0, verbose_name='Shop review stars'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.FloatField(default=0, verbose_name='Stars'),
        ),
    ]
