# Generated by Django 3.2.4 on 2021-07-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210702_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='author',
            field=models.CharField(blank=True, default='', max_length=125, null=True, verbose_name='Author'),
        ),
    ]
