# Generated by Django 3.2.4 on 2021-07-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_shop_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='rank',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.FloatField(default=0, null=True, verbose_name='Stars'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='product_no',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Number of products'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='review_no',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Number of review'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sale_no',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Number of sales'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='stars',
            field=models.FloatField(default=0, null=True, verbose_name='Shop review stars'),
        ),
    ]
