# Generated by Django 3.2.4 on 2021-07-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210702_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_review_date',
        ),
    ]
